name: Deploy latest release

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Check that workflows are up to date
        run: sbt Docker / publishLocal

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./target/docker/stage/Dockerfile
          push: true
          tags: amuxix/discordbot:latest, amuxix/discordbot:${{github.event.release.tag_name}}

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Fetch from dockerhub on remote
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSPHRASE }}
          key: ${{ secrets.KEY }}
          script: |
            docker pull amuxix/discordbot
            docker compose -f discordbot-compose.yml down
            docker compose -f discordbot-compose.yml up -d
